# Generated by Django 5.0.4 on 2025-08-01 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('david', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Expertise',
        ),
        migrations.AddField(
            model_name='about',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
