# Generated by Django 5.0.4 on 2025-08-01 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('david', '0003_expertise_remove_about_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educations',
            name='date',
            field=models.CharField(max_length=100),
        ),
    ]
