# Generated by Django 5.0.4 on 2025-08-01 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('david', '0004_alter_educations_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Performance',
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
