# Generated by Django 5.0.4 on 2025-08-01 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('david', '0005_delete_performance_portfolioitem_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioitem',
            name='date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
