# Generated by Django 5.0.4 on 2025-08-01 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('david', '0006_alter_portfolioitem_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='urlfiled',
            field=models.URLField(blank=True, null=True),
        ),
    ]
